# NOTE: docker-compose will create network automatically
# this allows the containers to communicate with each other
version: '2.1'

services:
  twitter-search:
    image: twitter-search
    container_name: twitter-search
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
  twitter-app:
    image: twitter-app
    container_name: twitter-app
    restart: always
    ports:
      - 5000:5000
    environment:
      - ELASTICSEARCH_URL=<your_ip>:9200
